public class Variables {
    //Local variables are declared with Java-style syntax. 
    //As with Java, multiple variables can be declared and initialized in a single statement.
    Integer i = 1000;
    String str = 'Apex Salesforce';
    //As with Java, multiple variables can be declared and initialized in a single statement, 
    //using comma separation.
    Integer  a = 100,b=200,c=300;
    //If you declare a variable and don't initialize it with a value, it will be null. 
    //In essence, null means the absence of a value. 
    //You can also assign null to any variable declared with a primitive type.
    Boolean x = null;
    Decimal d;

}